package com.daggerstudio.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table REC.
 */
public class Rec implements Serializable{

    private String site_url;
    /** Not-null value. */
    private String site_brief;
    /** Not-null value. */
    private String user_name;
    /** Not-null value. */
    private byte[] encypted_content;
    private String note;
    private Long id;

    public Rec() {
    }

    public Rec(Long id) {
        this.id = id;
    }

    public Rec(String site_url, String site_brief, String user_name, byte[] encypted_content, String note, Long id) {
        this.site_url = site_url;
        this.site_brief = site_brief;
        this.user_name = user_name;
        this.encypted_content = encypted_content;
        this.note = note;
        this.id = id;
    }

    public String getSite_url() {
        return site_url;
    }

    public void setSite_url(String site_url) {
        this.site_url = site_url;
    }

    /** Not-null value. */
    public String getSite_brief() {
        return site_brief;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSite_brief(String site_brief) {
        this.site_brief = site_brief;
    }

    /** Not-null value. */
    public String getUser_name() {
        return user_name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    /** Not-null value. */
    public byte[] getEncypted_content() {
        return encypted_content;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEncypted_content(byte[] encypted_content) {
        this.encypted_content = encypted_content;
    }

    public String getNote() {
        return note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
