package com.daggerstudio.password.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recDaoConfig;

    private final RecDao recDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recDaoConfig = daoConfigMap.get(RecDao.class).clone();
        recDaoConfig.initIdentityScope(type);

        recDao = new RecDao(recDaoConfig, this);

        registerDao(Rec.class, recDao);
    }
    
    public void clear() {
        recDaoConfig.getIdentityScope().clear();
    }

    public RecDao getRecDao() {
        return recDao;
    }

}
